### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by BigDeepBlue** [emiliskan/ugc_sprint_2#27]
Вообще хорошая работа, есть небольшие вопросы, но в целом все ок. Обратите внимание на комменты, вдруг вам удастся что-либо поправить

По CI:

- [Тут](https://github.com/emiliskan/ugc_sprint_2/blob/main/.github/workflows/python.yml#L5) нужно запускать флоу на каждый пуш в любую ветку, чтобы любой мог запушить и убедиться, что его код в порядке, особенно это актуально, если проверки долгие или тестов много и запускать локально не вариант. Ограничения для основной ветки актуальны только в случае с деплоем или сборкой. Ну и вдруг вы захотите отправить хотфикс в мастер мимо веток - тесты там тоже нужно проверить.
- Положите все [пакеты](https://github.com/emiliskan/ugc_sprint_2/blob/main/.github/workflows/python.yml#L27) в requirements. Выходит, что у вас локально и при проверке разные зависисмости? Это не очень хорошая практика-локально и на сервере форкфлоу может не выдавать одинаковый результат.
- if: always() Зачем?

По коду:
- А какой [алгоритм](https://github.com/emiliskan/ugc_sprint_2/blob/51775650dbea1c4f42d1836b8e2fa8693dd4127d/ugc_api/core/config.py#L22) вы используете? HS256? Рекомендую RS256 - асимметричный алгоритм, чтобы хранить в микросервисах только публичные ключи, а приватный для создания токенов будет только на auth. 
- Мне показалось немного сложноватым то, как вы храните скоринг у фильма, а также привязываетесь к скоринг айди так, что выносите его в [API](https://github.com/emiliskan/ugc_sprint_2/blob/51775650dbea1c4f42d1836b8e2fa8693dd4127d/ugc_api/api/v1/movie_scores.py#L33) и предлагаете клиенту его использовать (если я понял вас не верно, то значит еще и код в сервисе обработки скоринга у вас тоже сложноват). Вообще для получения суммарного скоринга по фильму должно хватать только movie_id, а для получения скоринга конкретного пользователя к конкретному фильму (для удаления и изменения) - пары user_id + movie_id. Поэтому я бы хранил все таки композитный primary key (_id) из этих двух полей или сделал compound index. У рецензий такой же подход, но там использование review_id уместно - в конце концов, у вас вполне может быть отдельная веб страница, где будет отображаться это ревью.
- Еще вы денормализуете данные (общий рейтинг) по фильму сразу в пришедшем запросе. Не самая хорошая практика - вполне можно в случае с высокой нагрузкой и одновременной простановкой оценок сотнями юзеров нарваться на расхождение. Лучше было бы сделать агрегацию налету - у нас же монго. нужно думать документоориентировано, так что вместо хранения списка ревью и оценок внутри документа с фильмом, нужно выгружать из отдельных collections. 

Насчет исследования:
- не хватает описания целей исследования и выводов для монго. Стоило бы сравнить с какой-нибудь другой базой результаты работы, так цифры просто повисли в воздухе. 
- Если цель - скорость работы то нужно совместить исследование с работой вашего сервиса - как быстро вся связка отдает данные, укдадывается ли в приемлемые 200мс

Про тесты:
- Вот [это](https://github.com/emiliskan/ugc_sprint_2/blob/51775650dbea1c4f42d1836b8e2fa8693dd4127d/ugc_api/tests/src/test_review_score.py#L9) хороший пример плохого теста. Идеальный тест содержит всего три строчки, разделенных пустой строкой: сетап, сам тест и assert результата. Также, само название теста должно быть говорящим. Вот этот тест точно можно разбить на несколько отдельных. Если один из них упадет, вы сразу узнаете, где при рефакториннге произошла проблема. А так если ваш test_review_scores упадет вы узнаете только то, что он упал. Причем остальные assert-ы после него вообще не отработают. Также не нужно оставлять комментарии в тестах. Если ваши тесты в python требуют комментариев - это тоже плохие тесты. Единственный комментарий в тесте - это его название `test_add_new_review_score`, `test_delete_review_score`, `test_get_reveiew_score`...

**Comment by emiliskan** [comment]
- if: always() Зачем? - Нужно например для запуска деплоя отчетов, даже если какой-то из других этапов выкинул ошибку

**Comment by vctecc** [comment]
По коду:

-  Используется HS256.  RS256  рассматривался, но решили тут не использовать: не требовалась доработка Auth сервиса в этом спринте плюс [вот эта](https://stackoverflow.com/questions/39239051/rs256-vs-hs256-whats-the-difference) мотивация.

**Comment by BigDeepBlue** [comment]
Спасибо вам за исправления, зачет!
