### ISSUE TITLE
Перписать get_movie_score

### ISSUE THREAD

**Issue by emiliskan** [emiliskan/ugc_sprint_2#29]
Нужно переписать на получение рейтинга фильма по movie_id

https://github.com/emiliskan/ugc_sprint_2/blob/51775650dbea1c4f42d1836b8e2fa8693dd4127d/ugc_api/api/v1/movie_scores.py#L33

Мне показалось немного сложноватым то, как вы храните скоринг у фильма, а также привязываетесь к скоринг айди так, что выносите его в API и предлагаете клиенту его использовать (если я понял вас не верно, то значит еще и код в сервисе обработки скоринга у вас тоже сложноват). Вообще для получения суммарного скоринга по фильму должно хватать только movie_id, а для получения скоринга конкретного пользователя к конкретному фильму (для удаления и изменения) - пары user_id + movie_id. Поэтому я бы хранил все таки композитный primary key (_id) из этих двух полей или сделал compound index. У рецензий такой же подход, но там использование review_id уместно - в конце концов, у вас вполне может быть отдельная веб страница, где будет отображаться это ревью.

**Comment by vctecc** [comment]
#29
