### ISSUE TITLE
Разделить большие функции тестов

### ISSUE THREAD

**Issue by emiliskan** [emiliskan/ugc_sprint_2#30]
- Вот [это](https://github.com/emiliskan/ugc_sprint_2/blob/51775650dbea1c4f42d1836b8e2fa8693dd4127d/ugc_api/tests/src/test_review_score.py#L9) хороший пример плохого теста. Идеальный тест содержит всего три строчки, разделенных пустой строкой: сетап, сам тест и assert результата. Также, само название теста должно быть говорящим. Вот этот тест точно можно разбить на несколько отдельных. Если один из них упадет, вы сразу узнаете, где при рефакториннге произошла проблема. А так если ваш test_review_scores упадет вы узнаете только то, что он упал. Причем остальные assert-ы после него вообще не отработают. Также не нужно оставлять комментарии в тестах. Если ваши тесты в python требуют комментариев - это тоже плохие тесты. Единственный комментарий в тесте - это его название `test_add_new_review_score`, `test_delete_review_score`, `test_get_reveiew_score`...

**Comment by vctecc** [comment]
#34
