### ISSUE TITLE
Сделать запуск проверок на push в любую ветку

### ISSUE THREAD

**Issue by emiliskan** [emiliskan/ugc_sprint_2#32]
- [Тут](https://github.com/emiliskan/ugc_sprint_2/blob/main/.github/workflows/python.yml#L5) нужно запускать флоу на каждый пуш в любую ветку, чтобы любой мог запушить и убедиться, что его код в порядке, особенно это актуально, если проверки долгие или тестов много и запускать локально не вариант. Ограничения для основной ветки актуальны только в случае с деплоем или сборкой. Ну и вдруг вы захотите отправить хотфикс в мастер мимо веток - тесты там тоже нужно проверить.

**Comment by vctecc** [comment]
#35
