### ISSUE TITLE
[3] Добаваить CI на основе github

### ISSUE THREAD

**Issue by vctecc** [emiliskan/ugc_sprint_2#7]
Исправить проверку линтерами.
        flake8 желательно заменить на wemake-python-styleguide
        Сделать вывод в красивый html-файл. В настройках линтеров есть такая опция.
    Добавить проверку типов с помощью mypy.
    Сделать проверку работоспособности кода на версиях python 3.7, 3.8 и 3.9. В этом поможет использование strategy.
    Добавить отправку сообщения об успешности прохождения CI в телеграм.
    Сделать срабатывание CI-процесса на новые pull request в master-ветку.
    Исправить все недочёты, найденные линтерами и статическими анализаторами.

**Comment by vctecc** [comment]
#19

**Comment by MaltsevaNata** [comment]
#21

**Comment by vctecc** [comment]
#25

**Comment by emiliskan** [comment]
у wemake-python-styleguide есть траблы, он не выводил мне ничего никуда, но в целом мы используем их версию flake, просто не action
